batch_normalization_enabled: true
classification_threshold: 0.54
convolutional_layer_sizes:
- 16
- 32
dataset_name: Tseep 1M
dense_layer_sizes:
- 16
evaluation_data_augmentation_enabled: true
event_onset_window_duration: 0.05
event_onset_window_start_time: 0.09
inference_waveform_start_time_offset: 0
l2_regularization_beta: 0.002
l2_regularization_enabled: false
max_waveform_time_shift: 0.025
min_classifier_recall: 0.98
model_input_name: Conv2D_0_input
num_dataset_parallel_calls: 4
num_training_steps: 30000
precision_recall_plot_lower_axis_limit: 0.8
precision_recall_plot_major_tick_interval: 0.05
precision_recall_plot_minor_tick_interval: 0.01
pretraining_batch_size: 100
pretraining_clipped_values_fraction: 0.001
pretraining_histogram_max: 50
pretraining_histogram_min: -25
pretraining_histogram_num_bins: 750
pretraining_num_examples: 20000
pretraining_value_distribution_plotting_enabled: false
random_waveform_time_shifting_enabled: true
spectrogram_clipping_enabled: true
spectrogram_clipping_max: 23.799999237060547
spectrogram_clipping_min: 1.399999976158142
spectrogram_clipping_pretraining_enabled: true
spectrogram_end_freq: 10000
spectrogram_hop_size: 50
spectrogram_log_epsilon: 1.0e-10
spectrogram_normalization_enabled: true
spectrogram_normalization_offset: -4.2332521979648385
spectrogram_normalization_pretraining_enabled: true
spectrogram_normalization_scale_factor: 0.3810824865669079
spectrogram_start_freq: 4000
spectrogram_window_size: 0.005
training_batch_size: 128
warm_start_enabled: true
waveform_duration: 0.19
waveform_initial_padding: 0.05
waveform_sample_rate: 24000
waveform_start_time: 0.039999999999999994
