# Template Docker Compose file for serving a Vesper archive using a
# Vesper Docker image.
#
# To use this file, copy it to the directory of the Vesper archive
# that you want to serve and name it `docker-compose.yaml`. Edit
# the file as described below for your situation. Then issue the
# `docker compose` commands listed below (or others) from that
# directory to start and stop the Vesper server, see its logs, etc.
#
# As is, this file runs a Docker image named `vesper` in a container
# to serve the Vesper archive of the current directory on port 8000.
# Edit the image name, the port number, and other settings below for
# your situation.
#
# This file also assumes that the `vesper` Python package is installed
# in the Docker image as a regular, non-editable Python package. If it
# is instead installed as an editable Python package, mount the package
# source code from the host into the container at the appropriate mount
# point in the `volumes` section below. See the commented-out example
# in that section for details.
#
# Once you have edited this file, you can issue the `docker compose`
# commands listed below (or others) from your archive directory to start
# and stop the Vesper server, see its logs, etc.
#
# To start the Vesper server in detached mode:
#
#     docker compose up -d
#
# To see logs when services are running in detached mode:
#
#     docker compose logs
#
# To stop the Vesper server:
#
#     docker compose down
#
# To collect static files:
#
#     docker compose up -d
#     docker compose exec vesper vesper_admin collectstatic
#
# To check if Vesper is safe to deploy:
#
#     docker compose up -d
#     docker compose exec vesper vesper_admin check --deploy
#
# See the _Django for Professionals_ security chapter (chapter 17 of the
# Django 4.0 version) for more.

name: vesper

services:

    vesper:

        image: vesper

        ports:
            - 8000:8000

        extra_hosts:
            - host.docker.internal:host-gateway
            
        # command: python /Code/vesper/django/manage.py test -p "dtest_*.py" vesper.django
        # command: python /Code/vesper/django/manage.py runserver 0.0.0.0:8000
        # command: gunicorn vesper.django.project.wsgi -w 4 -b 0.0.0.0:8000
        command: daphne vesper.django.project.asgi:application -b 0.0.0.0 -p 8000

        volumes:

            # The archive directory, mounted at `/Archive` in the container.
            - .:/Archive

            # If your Docker image containts a Vesper Python package that
            # is installed in editable mode, mount the package source code
            # from the host file system into the container's file system at
            # the appropriate mount point, as below. In the example, the
            # source code appears at `/Code` in the container.
            # - /Users/harold/Documents/Code/Python/vesper:/Code

        # Allow access to GPU.
        #deploy:
        #  resources:
        #    reservations:
        #      devices:
        #        - capabilities: [gpu]

        environment:

            # Django secret key. DO NOT USE THE KEY BELOW FOR A PUBLIC
            # VESPER WEB SITE. The key below is not secret since it is
            # publicly available in this file in the Vesper GitHub
            # repository. It is intended only as an example of the sort
            # of key to use. If you use it for a public Vesper site, you
            # will make it easy for a malicious actor to attack your site.
            #
            # To use this file for a public Vesper site, replace the key
            # below with your own that you keep secret. The key should be
            # a long sequence of randomly-generated characters. One way to
            # generate such a key (assuming that Python is installed on your
            # computer) is to execute the following (which was used to
            # generate the key below, but will generate a different key
            # every time you run it) at a command prompt or terminal:
            #
            #     python -c "import secrets; print(secrets.token_urlsafe(40))"
            VESPER_DJANGO_SECRET_KEY: "YKs482x7HnCKx1a7PvSf5zkRbvvn6nKRp6QSgiXjDLQg8_XPDPaoiw"

            VESPER_DJANGO_DEBUG: true

            VESPER_ARCHIVE_READ_ONLY: false
