batch_normalization_enabled: true
classification_threshold: 0.79
convolutional_layer_sizes:
- 16
- 32
dataset_name: Tseep 850K
dense_layer_sizes:
- 16
event_onset_window_duration: 0.05
event_onset_window_start_time: 0.09
inference_waveform_start_time_offset: 0
l2_regularization_beta: 0.002
l2_regularization_enabled: false
max_waveform_time_shift: 0.025
min_classifier_recall: 0.98
model_input_name: Conv2D_0_input
num_dataset_parallel_calls: 4
num_training_steps: 20000
precision_recall_plot_lower_axis_limit: 0.8
precision_recall_plot_major_tick_interval: 0.05
precision_recall_plot_minor_tick_interval: 0.01
pretraining_batch_size: 100
pretraining_clipped_values_fraction: 0.001
pretraining_histogram_max: 50
pretraining_histogram_min: -25
pretraining_histogram_num_bins: 750
pretraining_num_examples: 20000
pretraining_value_distribution_plotting_enabled: false
random_waveform_amplitude_scaling_enabled: true
random_waveform_time_shifting_enabled: true
spectrogram_clipping_enabled: true
spectrogram_clipping_max: 24.100000381469727
spectrogram_clipping_min: -1.7000000476837158
spectrogram_clipping_pretraining_enabled: true
spectrogram_end_freq: 10000
spectrogram_hop_size: 50
spectrogram_log_epsilon: 1e-10
spectrogram_normalization_enabled: true
spectrogram_normalization_offset: -4.27627110519542
spectrogram_normalization_pretraining_enabled: true
spectrogram_normalization_scale_factor: 0.3141718726591744
spectrogram_start_freq: 4000
spectrogram_window_size: 0.005
target_use: Detector
training_batch_size: 128
warm_start_enabled: false
waveform_duration: 0.19
waveform_initial_padding: 0.05
waveform_sample_rate: 24000
waveform_start_time: 0.039999999999999994
