batch_normalization_enabled: true
classification_threshold: 0.65
convolutional_layer_sizes:
- 16
- 32
dataset_name: Thrush 600K
dense_layer_sizes:
- 16
event_onset_window_duration: 0.08
event_onset_window_start_time: 0.11
inference_waveform_start_time_offset: 0.05
l2_regularization_beta: 0.002
l2_regularization_enabled: false
max_waveform_time_shift: 0.025
min_classifier_recall: 0.97
model_input_name: Conv2D_0_input
num_dataset_parallel_calls: 4
num_training_steps: 10000
precision_recall_plot_lower_axis_limit: 0.8
precision_recall_plot_major_tick_interval: 0.05
precision_recall_plot_minor_tick_interval: 0.01
pretraining_batch_size: 100
pretraining_clipped_values_fraction: 0.001
pretraining_histogram_max: 50
pretraining_histogram_min: -25
pretraining_histogram_num_bins: 750
pretraining_num_examples: 20000
pretraining_value_distribution_plotting_enabled: false
random_waveform_amplitude_scaling_enabled: true
random_waveform_time_shifting_enabled: true
spectrogram_clipping_enabled: true
spectrogram_clipping_max: 24.899999618530273
spectrogram_clipping_min: -0.6000000238418579
spectrogram_clipping_pretraining_enabled: true
spectrogram_end_freq: 5000
spectrogram_hop_size: 50
spectrogram_log_epsilon: 1e-10
spectrogram_normalization_enabled: true
spectrogram_normalization_offset: -4.605352065931508
spectrogram_normalization_pretraining_enabled: true
spectrogram_normalization_scale_factor: 0.30819157358811194
spectrogram_start_freq: 2000
spectrogram_window_size: 0.005
target_use: Detector
training_batch_size: 200
warm_start_enabled: false
waveform_duration: 0.25
waveform_initial_padding: 0.03
waveform_sample_rate: 24000
waveform_start_time: 0.08
